export default {
    crs: [
      { id: 1, text: 'Clinical Monitoring' },
      { id: 2, text: 'Clinical Quality Management' },
      { id: 3, text: 'Essential Regulatory Documents' },
      { id: 4, text: 'Medical Writing' },
      { id: 5, text: 'Protocol Development' },
      { id: 6, text: 'Protocol Deviation Reporting' },
      { id: 7, text: 'SAE Reporting' },
      { id: 8, text: 'Safety Oversight Committee' },
      { id: 9, text: 'Study Product Services' },
      { id: 10, text: 'Teleconference Support' },
    ],
    ServiceRequests: [
      { id: 1, text: 'Clinical Monitoring' },
      { id: 2, text: 'Clinical Monitoring Report' },
      { id: 3, text: 'Cinical Quality Management Services' },
      { id: 4, text: 'Cinical Quality Management Services Report' },
      { id: 5, text: 'CROMS Quality Crosswalk Review' },
      { id: 6, text: 'CROMS Quality Crosswalk Review Report' },
      { id: 7, text: 'DSMB-SMC Coordination' },
      { id: 8, text: 'DSMB-SMC Coordination Report' },
      { id: 9, text: 'Essential Regulatory Documents' },
      { id: 10, text: 'Essential Regulatory Documents Report' },
      { id: 11, text: 'Human Subjects Protection' },
      { id: 12, text: 'Medical Writing' },
      { id: 13, text: 'Medical Writing Report' },
      { id: 14, text: 'Miscellaneous Services' },
      { id: 15, text: 'Miscellaneous Services Report' },
      { id: 16, text: 'Report a Protocol Deviation' },
      { id: 17, text: 'Protocol Deviation Report' },
      { id: 18, text: 'Protocol Number Request' },
      { id: 19, text: 'Teleconference Support' },
      { id: 20, text: 'Teleconference Support Report' },
      { id: 21, text: 'Training' },
      { id: 22, text: 'Training Report' },
    ]    
  }